wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1740159880.699899
    t:
      1:
      - 12
      - 45
      - 55
      2:
      - 12
      - 45
      - 55
      3:
      - 13
      - 23
      4: 3.9.18
      5: 0.16.1
      8:
      - 4
      - 5
      13: darwin-arm64
